### ISSUE TITLE
Cannot build Simplenote iOS using M1 Apple Silicon

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-ios#1346]
When running `rake dependencies` to install all the prerequisites on a machine with the M1 Apple Silicon chip, it seems to fail at different points, but specially when attempting to install dependencies like `Cocoapods`.

Related issues:

- https://github.com/CocoaPods/CocoaPods/issues/10518
- https://github.com/CocoaPods/CocoaPods/issues/9907

I thought I was able to work around this by using Homebrew but it seems to fail for some other gems like `bigdecimal`, which I'm assuming is a dependency from `Cocoapods`: 

```
Traceback (most recent call last):
	26: from /usr/local/bin/bundle:23:in `<main>'
	25: from /usr/local/bin/bundle:23:in `load'
	24: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	23: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	22: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	21: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	20: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	19: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	18: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	17: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	16: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	14: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	12: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	11: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
	10: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
	 9: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:36:in `<top (required)>'
	 8: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:36:in `require'
	 7: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods.rb:9:in `<top (required)>'
	 6: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods.rb:9:in `require'
	 5: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	 4: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	 3: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	 2: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/xml_mini.rb:5:in `require'
	 1: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:2:in `<top (required)>'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:2:in `require': cannot load such file -- 2.6/bigdecimal.so (LoadError)
	27: from /usr/local/bin/bundle:23:in `<main>'
	26: from /usr/local/bin/bundle:23:in `load'
	25: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
	24: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
	23: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
	21: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	20: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
	19: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	18: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	17: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
	15: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
	14: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
	13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
	12: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/bin/pod:23:in `<top (required)>'
	11: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/bin/pod:23:in `load'
	10: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:36:in `<top (required)>'
	 9: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/bin/pod:36:in `require'
	 8: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods.rb:9:in `<top (required)>'
	 7: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods.rb:9:in `require'
	 6: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	 5: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	 4: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	 3: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.6/lib/active_support/xml_mini.rb:5:in `require'
	 2: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:1:in `<top (required)>'
	 1: from /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:4:in `rescue in <top (required)>'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.rb:4:in `require': dlopen(/Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle, 0x0009): missing compatible arch in /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle - /Users/iamgabrielma/Documents/iOS development/simplenote-ios/vendor/bundle/ruby/2.6.0/gems/bigdecimal-1.4.4/lib/bigdecimal.bundle (LoadError)
rake aborted!
Command failed with status (1): [bundle exec pod install...]
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/Rakefile:254:in `pod'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/Rakefile:73:in `block (4 levels) in <top (required)>'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/Rakefile:244:in `fold'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/Rakefile:72:in `block (3 levels) in <top (required)>'
/Users/iamgabrielma/Documents/iOS development/simplenote-ios/Rakefile:67:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => dependencies:pod:install
(See full trace by running task with --trace)
```
By checking the WordPress iOS repository I noticed this note:

> Please note – these setup instructions only apply to Intel-based machines. M1-based Mac support is coming, but isn't yet supported by our tooling.

I wonder if that's the case as well for Simplenote?

**Comment by jleandroperez** [comment]
Hey there @iamgabrielma !!

I'm afraid Apple Silicon support (for development) is not there yet. We don't really have a timeline yet for it.

cc @oguzkocer

**Comment by jkmassel** [comment]
It's possible (and somewhat well-documented elsewhere) how to run ruby entirely under rosetta, which should allow the use of Cocoapods. Longer-term, we plan to remove Cocoapods from the project which should resolve this nicely 😅

**Comment by iamgabrielma** [comment]
Thanks for the follow-up! For now I was able to build it with some workarounds:

I used `rbenv` for the Ruby version, in this case I went with `Ruby 2.7.3` , most of times this was failing when running `rake dependencies`, but this seems to have it resolved:

```
~$ bundle update ffi ethon
```

>       Installing ffi 1.15.3 (was 1.13.1) with native extensions
>       Installing ethon 0.14.0 (was 0.12.0)

```
~$ rake dependencies
```

>  Installing AppCenter (2.5.3)
Installing Automattic-Tracks-iOS (0.7.0)
Installing CocoaLumberjack (3.7.0)
Installing Gridicons (0.19)
Installing Reachability (3.2)
Installing Sentry (4.5.0)
Installing Simperium (1.8.0)
Installing Sodium-Fork (0.8.2)
Installing UIDeviceIdentifier (1.6.0)
Installing WordPress-Ratings-iOS (0.0.2)
Installing ZIPFoundation (0.9.11)

With this I was finally able to do the whole installation, then setting Xcode to run under Rosetta allowed to finally build Simplenote.

**Comment by charliescheer** [comment]
@iamgabrielma since you were able to get this building, I am gonna close this issue.  as @jkmassel mentioned, the long term plan is to get rid of cocoapods entirely, which will sort this all out

**Comment by jleandroperez** [comment]
Yes! We're dropping cocoapods soon-ish 😄
